#!/usr/bin/env bash

type -p amixer &>/dev/null || exec "$EXNOTIFY_SEND" -u low -r 15 'Install alsa-utils!'


Get_Perc="$(pactl list sinks | grep '^[[:space:]]Volume:' | \
	head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')"


case ${1} in
    up)   amixer set Master 5%+ && \
    	  exec ${HOME}/.scripts/notify/notify-send.sh -r 123 -t 700 -i "$HOME/.icons/UI/volume-medium.png" "Volume" " $Get_Perc% "
    ;;
    down) amixer set Master 5%- && \
    	  exec ${HOME}/.scripts/notify/notify-send.sh -r 123 -t 700 -i "$HOME/.icons/UI/volume-medium.png" "Volume" " $Get_Perc% " 
    ;;
    mute) amixer set Master toggle
          if pactl get-sink-mute 0 0 | grep "yes"; then
          exec "$HOME/.scripts/notify/notify-send.sh" -i $HOME/.icons/UI/Music.png -r 123 -t 700 'Muted '
  	  elif pactl get-sink-mute 0 0 | grep "no"; then
          exec "$HOME/.scripts/notify/notify-send.sh" -i $HOME/.icons/UI/Music.png -r 123 -t 700  'Alright, Unmuted'

          fi
    ;;
esac

notify

exit ${?}
